const f=document.getElementById('form');
const rbox=document.getElementById('result');
const loading=document.getElementById('loading');
const badge=document.getElementById('badge');
const score=document.getElementById('score');
const subject=document.getElementById('subject');
const reply=document.getElementById('reply');
const debug=document.getElementById('debug');
const debugContent=document.getElementById('debugContent');
const copyBtn=document.getElementById('copyBtn');
const fileInput=document.getElementById('file');
const modal=document.getElementById('modal');
const modalClose=document.getElementById('modalClose');
function showToast(t,ok=true){const e=document.createElement('div');e.className='toast '+(ok?'toast--ok':'toast--warn');e.textContent=t;document.body.appendChild(e);setTimeout(()=>{e.remove()},1600)}
fileInput.addEventListener('change',e=>{const file=e.target.files&&e.target.files[0];if(!file)return;if(file.name.toLowerCase().endsWith('.pdf')){modal.classList.remove('hidden')}});
modalClose.addEventListener('click',()=>modal.classList.add('hidden'));
f.addEventListener('submit',async e=>{e.preventDefault();rbox.classList.add('hidden');loading.classList.remove('hidden');const fd=new FormData();const txt=document.getElementById('raw_text').value||'';fd.append('raw_text',txt);const file=fileInput.files&&fileInput.files[0];if(file)fd.append('file',file);
const dbg=f.querySelector('input[name="return_debug"]').checked?'true':'false';
fd.append('return_debug',dbg);
try{const res=await fetch('/api/classificar',{method:'POST',body:fd});const data=await res.json().catch(()=>({detail:'Erro'}));if(!res.ok){throw new Error(data.detail||'Erro inesperado')}loading.classList.add('hidden');rbox.classList.remove('hidden');badge.textContent=data.category;score.textContent=(data.score*100).toFixed(1)+'%';subject.textContent=data.suggested_subject;reply.textContent=data.suggested_reply;rbox.classList.remove('result--produtivo','result--improdutivo');if(data.category==='Produtivo'){rbox.classList.add('result--produtivo');showToast('Classificado como Produtivo',true)}else{rbox.classList.add('result--improdutivo');showToast('Classificado como Improdutivo',false)}if(data.explanations){debug.classList.remove('hidden');debugContent.textContent=JSON.stringify(data.explanations,null,2)}else{debug.classList.add('hidden');debugContent.textContent=''}}catch(err){loading.classList.add('hidden');alert(err.message)}});
copyBtn.addEventListener('click',async()=>{await navigator.clipboard.writeText(reply.textContent);copyBtn.textContent='Copiado!';setTimeout(()=>copyBtn.textContent='Copiar resposta',1400)});
